### ISSUE TITLE
Error: '/usr/src/vips/lib/libvips-cpp.so': No such file

### ISSUE THREAD

**Issue by adamhayek1** [Newlywords/heroku-buildpack-vips#5]
Hey guys, I'm trying to use this buildpack to get PDF support for Sharp to work on Heroku. All goes well until Sharp tries to build from source and throws this error. Any idea what is causing this issue?

`readelf: Error: '/usr/src/vips/lib/libvips-cpp.so': No such file
gyp: Call to 'if readelf -Ws "$(PKG_CONFIG_PATH="/tmp/build_de8e195ae9ee65c6d0ee7803b4290341/.apt/usr/lib/x86_64-linux-gnu/pkgconfig:/tmp/build_de8e195ae9ee65c6d0ee7803b4290341/.apt/usr/lib/i386-linux-gnu/pkgconfig:/tmp/build_de8e195ae9ee65c6d0ee7803b4290341/.apt/usr/lib/pkgconfig::/tmp/build_de8e195ae9ee65c6d0ee7803b4290341/vendor/vips/lib/pkgconfig:/tmp/build_de8e195ae9ee65c6d0ee7803b4290341/.apt/usr/lib/x86_64-linux-gnu/pkgconfig:/tmp/build_de8e195ae9ee65c6d0ee7803b4290341/.apt/usr/lib/i386-linux-gnu/pkgconfig:/tmp/build_de8e195ae9ee65c6d0ee7803b4290341/.apt/usr/lib/pkgconfig::/usr/local/lib/pkgconfig:/usr/lib/pkgconfig" pkg-config --variable libdir vips-cpp)/libvips-cpp.so" | c++filt | grep -qF __cxx11;then echo "1";else echo "0";fi' returned exit status 0 while in binding.gyp. while trying to load binding.gyp`

**Comment by brandoncc** [comment]
I wish I did, but I don't. Your best bet would be to ask on stackoverflow. John Cupitt (creator of libvips) generally responds to libvips questions on there. He is awesome and super friendly. If we need to do something to the buildpack to make it work, I would consider it. Let me know how it goes.

**Comment by brandoncc** [comment]
I'm closing this due to inactivity. If you need to, feel free to reopen.

**Comment by lucashu1** [comment]
Hi! Sorry to revive this, but I'm getting a similar error with this buildpack (heroku-20) when trying to install sharp. The heroku build passes through this buildpack successfully, but installing `sharp` when installing the node modules raises some issues.

```
       > sharp@0.23.4 install /tmp/build_8a6aa47e/node_modules/sharp
       > (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
       
       info sharp Detected globally-installed libvips v8.10.6
       info sharp Building from source via node-gyp
       readelf: Error: '/usr/local/vips/lib/libvips-cpp.so': No such file
       gyp: Call to 'if readelf -Ws "$(PKG_CONFIG_PATH="/tmp/build_8a6aa47e/.apt/usr/lib/x86_64-linux-gnu/pkgconfig:/tmp/build_8a6aa47e/.apt/usr/lib/i386-linux-gnu/pkgconfig:/tmp/build_8a6aa47e/.apt/usr/lib/pkgconfig::/tmp/build_8a6aa47e/vendor/vips/lib/pkgconfig:/tmp/build_8a6aa47e/.apt/usr/lib/x86_64-linux-gnu/pkgconfig:/tmp/build_8a6aa47e/.apt/usr/lib/i386-linux-gnu/pkgconfig:/tmp/build_8a6aa47e/.apt/usr/lib/pkgconfig::/usr/local/lib/pkgconfig:/usr/lib/pkgconfig" pkg-config --variable libdir vips-cpp)/libvips-cpp.so" | c++filt | grep -qF __cxx11;then echo "1";else echo "0";fi' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
```

Any additional info since 2020 that might point toward a solution? I suppose the problem might also be with `sharp` and not necessarily with this buildpack, but I thought I'd check just in case.

I've been trying a few different ways to get `heic` support with `sharp` (running on heroku-20), but no luck so far. Hoping to be able to find a solution using this buildpack.

**EDIT:**
I think the issue might be that the `*.so` files are getting placed into the Heroku `/app` directory, and not into `/usr/local/...`? In other words, `$BUILD_DIR` doesn't match up with what the installation location that `sharp` is expecting.  Don't really know how this linking stuff works, so I'm admittedly kinda poking around in the dark -- but will continue to play around with this.

This is from after running `bash` into the Heroku dyno:
```
~/vendor/vips/lib $ ls
libde265.a	   libgif.a	    libgsf-1.a		  libheif.a	     liborc-0.4.la	   liborc-test-0.4.so	      libvips-cpp.so	      libvips.so
libde265.la	   libgif.la	    libgsf-1.la		  libheif.la	     liborc-0.4.so	   liborc-test-0.4.so.0       libvips-cpp.so.42       libvips.so.42
libde265.so	   libgif.so	    libgsf-1.so		  libheif.so	     liborc-0.4.so.0	   liborc-test-0.4.so.0.28.0  libvips-cpp.so.42.12.7  libvips.so.42.12.7
libde265.so.0	   libgif.so.7	    libgsf-1.so.114	  libheif.so.1	     liborc-0.4.so.0.28.0  libvips-cpp.a	      libvips.a		      pkgconfig
libde265.so.0.1.1  libgif.so.7.0.0  libgsf-1.so.114.0.42  libheif.so.1.10.0  liborc-test-0.4.la    libvips-cpp.la	      libvips.la
~/vendor/vips/lib $ pwd
/app/vendor/vips/lib
```

I guess we either need to tell `sharp` to look in `/app/vendor/vips/lib`, or somehow get the `*.so` files into `/usr/local/vips/lib` when running this buildpack.

**Edit 2:**
Tried changing `VIPS_PREFIX` from `/usr/local/vips` to `/app/vendor/vips`, and I'm still getting the same error:

```
info sharp Detected globally-installed libvips v8.10.6
       info sharp Building from source via node-gyp
       readelf: Error: '/app/vendor/vips/lib/libvips-cpp.so': No such file
       gyp: Call to 'if readelf -Ws "$(PKG_CONFIG_PATH="/tmp/build_b2299692/.apt/usr/lib/x86_64-linux-gnu/pkgconfig:/tmp/build_b2299692/.apt/usr/lib/i386-linux-gnu/pkgconfig:/tmp/build_b2299692/.apt/usr/lib/pkgconfig::/tmp/build_b2299692/vendor/vips/lib/pkgconfig:/tmp/build_b2299692/.apt/usr/lib/x86_64-linux-gnu/pkgconfig:/tmp/build_b2299692/.apt/usr/lib/i386-linux-gnu/pkgconfig:/tmp/build_b2299692/.apt/usr/lib/pkgconfig::/usr/local/lib/pkgconfig:/usr/lib/pkgconfig" pkg-config --variable libdir vips-cpp)/libvips-cpp.so" | c++filt | grep -qF __cxx11;then echo "1";else echo "0";fi' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
```

**Comment by lechinoix** [comment]
Just ran into the exact same problem trying to deploy my strapi instance with custom built vips. I also had the feeling after a few tests that the `lib/libvips-cpp.so` was found on `/app/vendor` rather than `/usr/local`, but if @lucashu1 tests are correct this might be something else 🤔 ?

I have been struggling with this for several hours, might be worth reopening the issue I think :)

```
error /tmp/build_ad69b80c/node_modules/sharp: Command failed.
remote:        Exit code: 1
remote:        Command: (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
remote:        Arguments:
remote:        Directory: /tmp/build_ad69b80c/node_modules/sharp
remote:        Output:
remote:        sharp: Detected globally-installed libvips v8.10.6
remote:        sharp: Building from source via node-gyp
remote:        readelf: Error: '/usr/local/vips/lib/libvips-cpp.so': No such file
remote:        gyp: Call to 'if readelf -Ws "$(PKG_CONFIG_PATH="/tmp/build_ad69b80c/.apt/usr/lib/x86_64-linux-gnu/pkgconfig:/tmp/build_ad69b80c/.apt/usr/lib/i386-linux-gnu/pkgconfig:/tmp/build_ad69b80c/.apt/usr/lib/pkgconfig::/tmp/build_ad69b80c/vendor/vips/lib/pkgconfig:/tmp/build_ad69b80c/.apt/usr/lib/x86_64-linux-gnu/pkgconfig:/tmp/build_ad69b80c/.apt/usr/lib/i386-linux-gnu/pkgconfig:/tmp/build_ad69b80c/.apt/usr/lib/pkgconfig::/usr/local/lib/pkgconfig:/usr/lib/pkgconfig" pkg-config --variable libdir vips-cpp)/libvips-cpp.so" | c++filt | grep -qF __cxx11;then echo "1";else echo "0";fi' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
remote:        gyp ERR! configure error
remote:        gyp ERR! stack Error: `gyp` failed with exit code: 1
remote:        gyp ERR! stack     at ChildProcess.onCpExit (/tmp/build_ad69b80c/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
remote:        gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
remote:        gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)
remote:        gyp ERR! System Linux 4.4.0-1097-aws
remote:        gyp ERR! command "/tmp/build_ad69b80c/.heroku/node/bin/node" "/tmp/build_ad69b80c/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
remote:        gyp ERR! cwd /tmp/build_ad69b80c/node_modules/sharp
remote:        gyp ERR! node -v v14.18.1
remote:        gyp ERR! node-gyp -v v5.1.0
remote:        gyp ERR! not ok
remote:        info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by lechinoix** [comment]
Okay so I tried the trick replacing `/usr/local` by `/app`, but it seems that Heroku is running npm install in a temporary build directory. Not really sure how it could be managed

![image](https://user-images.githubusercontent.com/10167015/140669335-112a9ece-ac28-4864-83f0-c20abf92a35a.png)

**Comment by lechinoix** [comment]
Fixed it by running a `heroku-predeploy` npm script :

```bash
TMP_DIR=$(pwd)

for file in $(grep -rl /usr/local ${TMP_DIR}/vendor/vips/lib/pkgconfig)
do
  sed -i "s+/usr/local+${TMP_DIR}/vendor+g" $file
done
```

If someone has a better option, I am not particularly proud of this ^^

**Comment by brandoncc** [comment]
Sorry for my lack of a response, I'm not sure when but I will look into this. I'm happy to see that there are at least some workarounds, even if they are not ideal.

**Comment by josephfrazier** [comment]
**EDIT: Fixed by adding `libfftw3-dev` to my `Aptfile`!** I also had to add `libpoppler-glib-dev` and `libpoppler-glib-dev`, so my `Aptfile` looks like this (for heroku-20 stack):

```
libglib2.0-0
libglib2.0-dev
libpoppler-glib8
libpoppler-glib-dev
libheif-dev
libfftw3-dev
libwebp-dev
```

---

Thanks for posting that workaround, @lechinoix! Once I added it as my `heroku-prebuild` script (not `heroku-predeploy`), my build got further!

However, I ran into another problem, and I'm curious whether you encountered the same thing: It can't find the `fftw3` package:

```
       [4/4] Building fresh packages...
       error /tmp/build_0178a9b8/node_modules/sharp: Command failed.
       Exit code: 1
       Command: (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
       Arguments: 
       Directory: /tmp/build_0178a9b8/node_modules/sharp
       Output:
       info sharp Detected globally-installed libvips v8.10.6
       info sharp Building from source via node-gyp
       Package fftw3 was not found in the pkg-config search path.
       Perhaps you should add the directory containing `fftw3.pc'
       to the PKG_CONFIG_PATH environment variable
       Package 'fftw3', required by 'vips', not found
       gyp: Call to 'PKG_CONFIG_PATH="/tmp/build_0178a9b8/.apt/usr/lib/x86_64-linux-gnu/pkgconfig:/tmp/build_0178a9b8/.apt/usr/lib/i386-linux-gnu/pkgconfig:/tmp/build_0178a9b8/.apt/usr/lib/pkgconfig::/tmp/build_0178a9b8/vendor/vips/lib/pkgconfig:/tmp/build_0178a9b8/.apt/usr/lib/x86_64-linux-gnu/pkgconfig:/tmp/build_0178a9b8/.apt/usr/lib/i386-linux-gnu/pkgconfig:/tmp/build_0178a9b8/.apt/usr/lib/pkgconfig::/usr/local/lib/pkgconfig:/usr/lib/pkgconfig" pkg-config --cflags-only-I vips-cpp vips glib-2.0 | sed s\/-I//g' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
       gyp ERR! configure error 
       gyp ERR! stack Error: `gyp` failed with exit code: 1
       gyp ERR! stack     at ChildProcess.onCpExit (/tmp/build_0178a9b8/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:259:16)
       gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
       gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
       gyp ERR! System Linux 4.4.0-1097-aws
       gyp ERR! command "/tmp/build_0178a9b8/.heroku/node/bin/node" "/tmp/build_0178a9b8/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
       gyp ERR! cwd /tmp/build_0178a9b8/node_modules/sharp
       gyp ERR! node -v v16.13.0
       gyp ERR! node-gyp -v v8.4.0
       gyp ERR! not ok
```

**Comment by brandoncc** [comment]
I don't know if it is the same package that you are needing, but I found a
package called cl-fftw3. If that is the one you need, I would try adding it
to your .Aptfile. I think that should resolve these issue.

**Comment by josephfrazier** [comment]
Thanks, I did eventually find the right set of packages for my use case, and edited them into the comment above!
