### ISSUE TITLE
500's after latest changes

### ISSUE THREAD

**Issue by dp6ai** [Newlywords/heroku-buildpack-vips#8]
Since this morning i have started getting 500's on my heroku instance with the following error messages. 

I assume its related to this [change](https://github.com/brandoncc/heroku-buildpack-vips/commit/fd2403151824559834b07b2419e03654cdb08ce9) 

```LoadError (Could not open library 'vips.so.42': vips.so.42: cannot open shared object file: No such file or directory.
2020-09-21T10:25:49.585977+00:00 app[web.1]: Could not open library 'libvips.so.42': libwebpmux.so.3: cannot open shared object file: No such file or directory):
2020-09-21T10:25:49.585978+00:00 app[web.1]: [87e314a0-905e-4c6f-b66c-117803df07ae]
```

**Comment by dp6ai** [comment]
I've tried explicitly stating this [commit](https://github.com/brandoncc/heroku-buildpack-vips/commit/6d1895def2c82371e3c2c64ae2ec07ab5be1fccd) in the app.json and its still failing. 

**Edited**

**I can confirm the above commit does solve the problem for me. Thanks**



I get 1000's of lines like this 

```
-----> Running test command `bundle exec rspec`...
...F/app/vendor/bundle/ruby/2.6.0/gems/ruby-vips-2.0.17/lib/

/app/vendor/bundle/ruby/2.6.0/gems/ruby-vips-2.0.17/lib/vips.rb:51: warning: previous definition of G_FREE was here
/app/vendor/bundle/ruby/2.6.0/gems/ruby-vips-2.0.17/lib/vips.rb:59: warning: already initialized constant GLib::LOG_FLAG_RECURSION
/app/vendor/bundle/ruby/2.6.0/gems/ruby-vips-2.0.17/lib/vips.rb:59: warning: previous definition of LOG_FLAG_RECURSION was here
/app/vendor/bundle/ruby/2.6.0/gems/ruby-vips-2.0.17/lib/vips.rb:60: warning: already initialized constant GLib::LOG_FLAG_FATAL
/app/vendor/bundle/ruby/2.6.0/gems/ruby-vips-2.0.17/lib/vips.rb:60: warning: previous definition of LOG_FLAG_FATAL was here
/app/vendor/bundle/ruby/2.6.0/gems/ruby-vips-2.0.17/lib/vips.rb:63: warning: already initialized constant GLib::LOG_LEVEL_ERROR
/app/vendor/bundle/ruby/2.6.0/gems/ruby-vips-2.0.17/lib/vips.rb:63: warning: previous definition of LOG_LEVEL_ERROR was here
/app/vendor/bundle/ruby/2.6.0/gems/ruby-vips-2.0.17/lib/vips.rb:64: warning: already initialized constant GLib::LOG_LEVEL_CRITICAL
/app/vendor/bundle/ruby/2.6.0/gems/ruby-vips-2.0.17/lib/vips.rb:64: warning: previous definition of LOG_LEVEL_CRITICAL was here
/app/vendor/bundle/ruby/2.6.0/gems/ruby-vips-2.0.17/lib/vips.rb:65: warning: already initialized constant GLib::LOG_LEVEL_WARNING
/app/vendor/bundle/ruby/2.6.0/gems/ruby-vips-2.0.17/lib/vips.rb:65: warning: previous definition of LOG_LEVEL_WARNING was here
/app/vendor/bundle/ruby/2.6.0/gems/ruby-vips-2.0.17/lib/vips.rb:66: warning: already initialized constant GLib::LOG_LEVEL_MESSAGE
/app/vendor/bundle/ruby/2.6.0/gems/ruby-vips-2.0.17/lib/vips.rb:66: warning: previous definition of LOG_LEVEL_MESSAGE was here
/app/vendor/bundle/ruby/2.6.0/gems/ruby-vips-2.0.17/lib/vips.rb:67: warning: already initialized constant GLib::LOG_LEVEL_INFO
/app/vendor/bundle/ruby/2.6.0/gems/ruby-vips-2.0.17/lib/vips.rb:67: warning: previous definition of LOG_LEVEL_INFO was here
/app/vendor/bundle/ruby/2.6.0/gems/ruby-vips-2.0.17/lib/vips.rb:68: warning: already initialized constant GLib::LOG_LEVEL_DEBUG
/app/vendor/bundle/ruby/2.6.0/gems/ruby-vips-2.0.17/lib/vips.rb:68: warning: previous definition of LOG_LEVEL_DEBUG was here
/app/vendor/bundle/ruby/2.6.0/gems/ruby-vips-2.0.17/lib/vips.rb:71: warning: already initialized constant GLib::GLIB_TO_SEVERITY
/app/vendor/bundle/ruby/2.6.0/gems/ruby-vips-2.0.17/lib/vips.rb:71: warning: previous definition of GLIB_TO_SEVERITY was here
/app/vendor/bundle/ruby/2.6.0/gems/ruby-vips-2.0.17/lib/vips.rb:86: warning: already initialized constant GLib::LOG_HANDLER
/app/vendor/bundle/ruby/2.6.0/gems/ruby-vips-2.0.17/lib/vips.rb:86: warning: previous definition of LOG_HANDLER was here
```



followed by  

```
Failures:
  1) Browsing An admin has the correct navigation
     Failure/Error: image.respond_to?(:variant) ? Rails.application.routes.url_helpers.rails_representation_url(image.variant(attributes).processed, only_path: true) : image_path("os_alternative.png")
     LoadError:
       Could not open library 'vips.so.42': vips.so.42: cannot open shared object file: No such file or directory.
       Could not open library 'libvips.so.42': libwebpmux.so.3: cannot open shared object file: No such file or director
```

**Comment by dp6ai** [comment]
and on the server 

```
~ $ which vips
/app/vendor/vips/bin/vips
~ $ vips --version
vips: error while loading shared libraries: libwebpmux.so.3: cannot open shared object file: No such file or directory
~ $
```

**Comment by hadees** [comment]
I can't deploy, getting similar problems.

```
remote:  !
remote:  !     Could not detect rake tasks
remote:  !     ensure you can run `$ bundle exec rake -P` against your app
remote:  !     and using the production group of your Gemfile.
remote:  !     rake aborted!
remote:  !     LoadError: Could not open library 'vips.so.42': vips.so.42: cannot open shared object file: No such file or directory.
remote:  !     Could not open library 'libvips.so.42': libwebpmux.so.3: cannot open shared object file: No such file or directory
remote:  !     /tmp/build_9927a046/vendor/bundle/ruby/2.7.0/gems/ffi-1.13.1/lib/ffi/library.rb:145:in `block in ffi_lib'
remote:  !     /tmp/build_9927a046/vendor/bundle/ruby/2.7.0/gems/ffi-1.13.1/lib/ffi/library.rb:99:in `map'
remote:  !     /tmp/build_9927a046/vendor/bundle/ruby/2.7.0/gems/ffi-1.13.1/lib/ffi/library.rb:99:in `ffi_lib'
remote:  !     /tmp/build_9927a046/vendor/bundle/ruby/2.7.0/gems/ruby-vips-2.0.17/lib/vips.rb:528:in `<module:Vips>'
remote:  !     /tmp/build_9927a046/vendor/bundle/ruby/2.7.0/gems/ruby-vips-2.0.17/lib/vips.rb:525:in `<main>'
remote:  !     /tmp/build_9927a046/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
remote:  !     /tmp/build_9927a046/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
remote:  !     /tmp/build_9927a046/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
remote:  !     /tmp/build_9927a046/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
remote:  !     /tmp/build_9927a046/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
remote:  !     /tmp/build_9927a046/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/dependencies.rb:324:in `block in require'
remote:  !     /tmp/build_9927a046/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/dependencies.rb:291:in `load_dependency'
remote:  !     /tmp/build_9927a046/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/dependencies.rb:324:in `require'
remote:  !     /tmp/build_9927a046/vendor/bundle/ruby/2.7.0/gems/ruby-vips-2.0.17/lib/ruby-vips.rb:1:in `<main>'
remote:  !     /tmp/build_9927a046/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
remote:  !     /tmp/build_9927a046/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
remote:  !     /tmp/build_9927a046/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
remote:  !     /tmp/build_9927a046/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
remote:  !     /tmp/build_9927a046/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
remote:  !     /tmp/build_9927a046/vendor/ruby-2.7.1/lib/ruby/2.7.0/bundler/runtime.rb:74:in `block (2 levels) in require'
remote:  !     /tmp/build_9927a046/vendor/ruby-2.7.1/lib/ruby/2.7.0/bundler/runtime.rb:69:in `each'
remote:  !     /tmp/build_9927a046/vendor/ruby-2.7.1/lib/ruby/2.7.0/bundler/runtime.rb:69:in `block in require'
remote:  !     /tmp/build_9927a046/vendor/ruby-2.7.1/lib/ruby/2.7.0/bundler/runtime.rb:58:in `each'
remote:  !     /tmp/build_9927a046/vendor/ruby-2.7.1/lib/ruby/2.7.0/bundler/runtime.rb:58:in `require'
remote:  !     /tmp/build_9927a046/vendor/ruby-2.7.1/lib/ruby/2.7.0/bundler.rb:174:in `require'
remote:  !     /tmp/build_9927a046/config/application.rb:17:in `<main>'
remote:  !     /tmp/build_9927a046/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
remote:  !     /tmp/build_9927a046/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
remote:  !     /tmp/build_9927a046/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
remote:  !     /tmp/build_9927a046/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
remote:  !     /tmp/build_9927a046/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
remote:  !     /tmp/build_9927a046/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/dependencies.rb:324:in `block in require'
remote:  !     /tmp/build_9927a046/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/dependencies.rb:291:in `load_dependency'
remote:  !     /tmp/build_9927a046/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/dependencies.rb:324:in `require'
remote:  !     /tmp/build_9927a046/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:53:in `require_relative'
remote:  !     /tmp/build_9927a046/Rakefile:6:in `<main>'
remote:  !     /tmp/build_9927a046/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
remote:  !     /tmp/build_9927a046/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
remote:  !     /tmp/build_9927a046/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/dependencies.rb:318:in `block in load'
remote:  !     /tmp/build_9927a046/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/dependencies.rb:291:in `load_dependency'
remote:  !     /tmp/build_9927a046/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/dependencies.rb:318:in `load'
remote:  !     /tmp/build_9927a046/vendor/bundle/ruby/2.7.0/gems/rake-13.0.1/lib/rake/rake_module.rb:29:in `load_rakefile'
remote:  !     /tmp/build_9927a046/vendor/bundle/ruby/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:703:in `raw_load_rakefile'
remote:  !     /tmp/build_9927a046/vendor/bundle/ruby/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:104:in `block in load_rakefile'
remote:  !     /tmp/build_9927a046/vendor/bundle/ruby/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:186:in `standard_exception_handling'
remote:  !     /tmp/build_9927a046/vendor/bundle/ruby/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:103:in `load_rakefile'
remote:  !     /tmp/build_9927a046/vendor/bundle/ruby/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:82:in `block in run'
remote:  !     /tmp/build_9927a046/vendor/bundle/ruby/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:186:in `standard_exception_handling'
remote:  !     /tmp/build_9927a046/vendor/bundle/ruby/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:80:in `run'
remote:  !     /tmp/build_9927a046/bin/rake:9:in `<main>'
remote:  !
```

**Comment by hadees** [comment]
So replacing the buildpack with `https://github.com/brandoncc/heroku-buildpack-vips#6d1895def2c82371e3c2c64ae2ec07ab5be1fccd` also worked for me, following Heroku's [documentation](https://devcenter.heroku.com/articles/buildpacks#buildpack-references).

Maybe we can use this issue now as a way to know when I can unpin this?  Seems like you wouldn't want to do this forever.

**Comment by brandoncc** [comment]
I just saw this in our own app too, sorry! I'm not sure what broke. Working on it now.

**Comment by brandoncc** [comment]
Sorry everyone, I didn't think there would be any issues because it built fine. I reverted my changes for now, and will test them before putting those changes back in master. Feel free to keep your apps pinned to the revisions, but that will keep you from getting version updates :-/

I'm going to try to have this resolved today.

**Comment by jonknapp** [comment]
For what it's worth, I just did a deploy with the following buildpacks and did not have to pin to a specific release:

1. heroku-community/apt
2. https://github.com/brandoncc/heroku-buildpack-vips

`Aptfile` has:

```
libglib2.0-0
libglib2.0-dev
libpoppler-glib8
```

------

I don't believe other buildpacks impacted anything, but just in case:

3. https://github.com/heroku/heroku-buildpack-activestorage-preview
4. heroku/nodejs
5. heroku/ruby

**Comment by brandoncc** [comment]
Thanks @jonknapp. I reverted the breaking changes, so that all sounds right. I haven't had a chance yet to dig into making the originally-intended fix again yet.

**Comment by hogeman-hoges** [comment]
Note: This buildpack is still broken. Regarding the above:
```
For what it's worth, I just did a deploy with the following buildpacks and did not have to pin to a specific release:

    heroku-community/apt
    https://github.com/brandoncc/heroku-buildpack-vips

Aptfile has:

libglib2.0-0
libglib2.0-dev
libpoppler-glib8

I don't believe other buildpacks impacted anything, but just in case:

    https://github.com/heroku/heroku-buildpack-activestorage-preview
    heroku/nodejs
    heroku/ruby
```
It ONLY works if `heroku/nodejs` is set as a buildpack before `heroku/ruby`. When it isn't, `LD_LIBRARY_PATH` does not include the proper vips vendor lib paths, leading to the shared library error. This must be a problem somewhere in the code where the path is either incorrectly set, or unset after some changes.

**Comment by brandoncc** [comment]
That is very interesting! I actually have `heroku/nodejs` setup exactly as you mentioned in my projects, so I didn't know about this. Thanks for bringing it up. I'll put it on my todo list to work on it and see if I can identify the problem. I'll try to do it on Sunday.

**Comment by brandoncc** [comment]
I don't think this is a problem anymore, because I'm using the buildpack on servers without the nodejs buildpack. I'm going to close the issue, but feel free to re-open it if the problem resurfaces.

**Comment by jon-sully** [comment]
Hey @brandoncc! I think there is still an issue with this, though I'm not sure exactly what it is yet. I'm chatting with John Cupitt over on https://github.com/libvips/ruby-vips/issues/219 about it too but I received this very same error on a new install of the buildpack yesterday. Had to end up going with a pure Aptfile approach that makes a massive slug, but let me go ahead and spin up a new staging app with the buildpack again to see if I can repro the error to give you some context.

**Comment by jon-sully** [comment]
I was wrong 😄. Just spent an hour playing with the buildpack and while I had initially thought that I could leave `libpoppler` out of the `Aptfile` because my app doesn't do any work with pdfs, that's what was causing this error. Added it to the Aptfile (still with `libglib2.0-0` and `libglib2.0-dev`) and things worked just fine. Thanks y'all!

EDIT: Hate to be the guy that doesn't follow the instructions..

> you must install these packages in your heroku application

then makes suggestions 🤦 but it may be worth calling out in the README that `libpoppler` is required even if you have no intention to work with Pdfs for smart-alecs like me that think it'll just work without. 😅
